version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    container_name: nexus_studios
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - data:/data/db

volumes:
  data: